var tracce = [
  { id: "pagina1-3", unita: "Ciao", pagina: "Pagina 1-3", titolo: "Alfabeto italiano", file: "ALFABETO.mp3" },
  { id: "pagina4", unita: "Ciao", pagina: "Pagina 4", titolo: "Presentarsi", file: "PRESENTARSI.mp3" },
  { id: "pagina5", unita: "Ciao", pagina: "Pagina 5", titolo: "Saluti", file: "SALUTI.mp3" },
  { id: "pagina6", unita: "Ciao", pagina: "Pagina 6", titolo: "Suoni dolci (C)", file: "SUONO_DOLCE_C.mp3" },
  { id: "pagina7", unita: "Ciao", pagina: "Pagina 7", titolo: "Suoni duri (C)", file: "SUONI_DURI_C.mp3" },
  { id: "pagina9", unita: "Ciao", pagina: "Pagina 9", titolo: "Suoni dolci (G)", file: "SUONO_DOLCE_G.mp3" },
  { id: "pagina10", unita: "Ciao", pagina: "Pagina 10", titolo: "Suoni duri (G)", file: "SUONI_DURI_G.mp3" },
  { id: "pagina12", unita: "Ciao", pagina: "Pagina 12", titolo: "Giorni della settimana", file: "GIORNI_DELLA_SETTIMANA.mp3" },
  { id: "pagina13", unita: "Ciao", pagina: "Pagina 13", titolo: "Mesi dell'anno", file: "MESI_DELL_ANNO.mp3" },
  { id: "pagina14-15", unita: "Ciao", pagina: "Pagina 14-15", titolo: "Numeri (1-20)", file: "NUMERI_DA_1_A_20.mp3" },

  { id: "pagina17-18", unita: "Di dove sei", pagina: "Pagina 17-18", titolo: "Presentarsi (Lui/Lei)", file: "PRESENTARSI2.mp3" },
  { id: "pagina20", unita: "Di dove sei", pagina: "Pagina 20", titolo: "La negazione (Non)", file: "NON.mp3" },
  { id: "pagina21", unita: "Di dove sei", pagina: "Pagina 21", titolo: "Nazionalità", file: "NAZIONALITA.mp3" },
  { id: "pagina22", unita: "Di dove sei", pagina: "Pagina 22", titolo: "Nazionalità e Continenti", file: "CONTINENTI.mp3" },
  { id: "pagina23", unita: "Di dove sei", pagina: "Pagina 23", titolo: "Colori", file: "COLORI.mp3" },
  { id: "pagina24-25", unita: "Di dove sei", pagina: "Pagina 24-25", titolo: "Verbo Essere", file: "VERBO_ESSERE.mp3" },

  { id: "pagina26", unita: "Quanti anni hai", pagina: "Pagina 26", titolo: "Quanti anni hai?", file: "QUANTI_ANNI_HAI.mp3" },
  { id: "pagina27", unita: "Quanti anni hai", pagina: "Pagina 27", titolo: "Hai una macchina?", file: "HAI_UNA_MACCHINA.mp3" },
  { id: "pagina28", unita: "Quanti anni hai", pagina: "Pagina 28", titolo: "Ho mal di testa", file: "HO_MAL_DI_TESTA.mp3" },
  { id: "pagina29-30", unita: "Quanti anni hai", pagina: "Pagina 29-30", titolo: "Verbo Avere", file: "VERBO_AVERE.mp3" },
  { id: "pagina31", unita: "Quanti anni hai", pagina: "Pagina 31", titolo: "Voglia / Bisogno", file: "HO_VOGLIA_DI_BISOGNO_DI.mp3" },
  { id: "pagina32", unita: "Quanti anni hai", pagina: "Pagina 32", titolo: "Suoni difficili (GLI)", file: "SUONO_GLI.mp3" },
  { id: "pagina33", unita: "Quanti anni hai", pagina: "Pagina 33", titolo: "Suoni difficili (GN)", file: "SUONO_GN.mp3" },

  { id: "pagina34", unita: "Impara facile", pagina: "Pagina 34", titolo: "Presentazione (Priya)", file: "PRIYA.mp3" },
  { id: "pagina35-36", unita: "Impara facile", pagina: "Pagina 35-36", titolo: "Numeri (21-1.000.000)", file: "NUMERI_DA_21_A_1_MILIONE.mp3" },
  { id: "pagina41", unita: "Impara facile", pagina: "Pagina 41", titolo: "Dove lavori?", file: "DOVE_LAVORI.mp3" },
  { id: "pagina42", unita: "Impara facile", pagina: "Pagina 42", titolo: "Suoni dolci (SC)", file: "SUONO_SOLCE_SC_I_E.mp3" },
  { id: "pagina43", unita: "Impara facile", pagina: "Pagina 43", titolo: "Suoni duri (SC)", file: "SUONI_DURI_SC.mp3" },

  { id: "pagina44-46", unita: "Are-Ere-Ire", pagina: "Pagina 44-46", titolo: "Verbi in -ARE", file: "VERBI_ARE.mp3" },
  { id: "pagina45", unita: "Are-Ere-Ire", pagina: "Pagina 45", titolo: "Abiti qui vicino?", file: "ABITI_QUI_VICINI.mp3" },
  { id: "pagina47-49", unita: "Are-Ere-Ire", pagina: "Pagina 47-49", titolo: "Verbi in -ERE", file: "VERBI_ERE.mp3" },
  { id: "pagina48", unita: "Are-Ere-Ire", pagina: "Pagina 48", titolo: "Che cosa leggi?", file: "CHE_COSA_LEGGI.mp3" },
  { id: "pagina50-52", unita: "Are-Ere-Ire", pagina: "Pagina 50-52", titolo: "Verbi in -IRE", file: "VERBI_IRE.mp3" },
  { id: "pagina51", unita: "Are-Ere-Ire", pagina: "Pagina 51", titolo: "Senti caldo?", file: "SANTI_CALDO.mp3" }
];
